### PR TITLE
Check if PIXI.Point.copy exists, else use copyForm

### LINKED ISSUE #120: PIXI.Point.copy() deprecated in v5, causes setPixiValue() to break
### Description

http://pixijs.download/release/docs/PIXI.Point.html#copy

https://github.com/michalochman/react-pixi-fiber/blob/42c2522c67d173a79b708e4dae24584b82ba4afe/src/utils.js#L60

Managed to fix by updating `copy` to `copyFrom`.

I could push a PR that checks for whichever exists and use it if you're ok with that, unless you have something else planned?

### Steps to reproduce

Not my codebase but roughly something like this

```
import { Text } from 'react-pixi-fiber';
...
render = () => {
    return (
      <Text
        position={new Point(1 ,1)}
      />
    );
  };
``` 

### Additional info

- react-pixi-fiber version: 0.8.1
- React version: 16.8.5
- ReactDOM version: 16.8.5
- PixiJS version: 5.0.4

### PR DESCRIPTION
**Pull request by SenHeng**
Fixes #120

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -57,7 +61,14 @@ export function isPointType(value) {
 export function setPixiValue(instance, propName, value) {
   if (isPointType(instance[propName]) && isPointType(value)) {
     // Just copy the data if a Point type is being assigned to a Point type
-    instance[propName].copy(value);
+
+    // Copy was deprecated and renamed to copyForm in PIXI 5.0
+    // Use whichever exists
+    if (hasCopyFunction(instance[propName])) {
```
Comment (michalochman) [inline src/utils.js]: I think it would be better to extract this logic to a function called for example `copyPoint(instance, propName, value)` than to just create and use `hasCopyFunction` function.

File: CONTRIBUTING.md [hunk 2]
```diff
@@ -45,14 +45,13 @@ The core team is monitoring for pull requests. We will review your pull request
 3. If you've fixed a bug or added code that should be tested, add tests!
 4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.
 5. Format your code with [prettier](https://github.com/prettier/prettier) (`yarn prettier`).
-6. Make sure your code lints (`yarn lint`).
-
+6. Make sure your code lints (`yarn eslint`).
```
Comment (michalochman) [inline CONTRIBUTING.md]: Good catch 👍

File: src/utils.js (hunk 1 above)
Comment (SenHeng) [reply src/utils.js]: I've made the changes.

Comment (michalochman) [reply src/utils.js]: Splendid, but you forgot about the test you wrote ;) I'll merge and release this as soon as the build is passing.

Comment (SenHeng) [reply src/utils.js]: whoops

Comment (SenHeng) [reply src/utils.js]: I've updated the tests and included a check for whether it's using PIXI v4 or v5.

**Comment by SenHeng** [comment]
TIL. I wasn't familiar with Jest, thanks!
